export enum SendStatusType {
  'WAIT_HANDLING' = 0,
  'SUCCESS' = 1,
  'CANCELED' = 2,
  'EXCEPTION_FAILED' = 100,
  'READY_DEPENDENCY_FAILED' = 101,
  'REPLAY_CASE_NOT_FOUND' = 102,
  'REPLAY_RESULT_NOT_FOUND' = 103,
}
